### ISSUE TITLE
[Bug]: Stuck in Attempting to find X

### ISSUE THREAD

**Issue by DanMaklen** [Mrbysco/StructureCompass#17] opened 2023-12-30 18:35 UTC
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.16

### Minecraft version

1.21.1

### Mod version

2.0.7

### Java version

openjdk 17.0.8 2023-07-18 LTS

### Issue Description

**Mod pack:** ATM9

I configure the compass to search for `minecraft:jungle_pyramid`:
- `Attempting to locate minecraft:jungle_pyramid, please wait...` appears
- Any kind of interaction with the game world doesn't register (e.g. breaking blocks don't drop items)
- After waiting for few minutes, still stuck

Attempts done:
- running command `/locate structure minecraft:jungle_pyramid`:
  - I get response: `Use /locate structure betterjungletemples:jungle_temple instead!`
- running `/locate structure betterjungletemples:jungle_temple':
  - Works: `The nearest betterjungletemples:jungle_temple is at [--1952, ~, 3440] (2836 blocks away)`
- Using the compass to search for `betterjungletemples:jungle_temple`:
  - Works: `betterjungletemples:jungle_temple has been located 3729 blocks away, compass is pointing towards the structure`

### Additional Information

[latest.log](https://github.com/Mrbysco/StructureCompass/files/13798923/latest.log)
![Screenshot 2023-12-30 203108](https://github.com/Mrbysco/StructureCompass/assets/9917244/af36a8bd-7a23-4f1e-8295-3a58a80023c8)

**Comment by Mrbysco** [comment] 2023-12-30 18:54
This is basically a duplicate of #16

**Comment by Mrbysco** [comment] 2023-12-30 18:55
The compass has no knowledge of what structures have been removed from the world and will still try to locate them, there's not much I can do about that. ATM could blacklist the structures from showing up

**Comment by Mrbysco** [comment] 2024-03-08 22:06
A new version will be up shortly with a config option that makes structure locating asynchronous, please enable it and tell me if it fixes the problem

**Comment by Mrbysco** [comment] 2024-05-24 19:39
I'm going to close this issue for lack of response. If it persists the issue can be re-opened

**Closed as completed by Mrbysco** 2024-05-24 19:39 UTC
Labels: bug
